### ISSUE TITLE
Imgui Empty ID Assertion triggered after reloading tracking tree

### ISSUE THREAD

**Issue by grillo-delmal** [Inochi2D/inochi-session#1]
How to reproduce:
* Open inochi-session with a model
* Ensure that the Tracking popup is visible ( View -> Tracking)
* Click on the model
* Click the refresh button
* Open one of the combo boxes

Doing this produces the following error message:
inochi-session: /opt/src/bindbc-imgui/deps/cimgui/imgui/imgui.cpp:8925: bool ImGui::ItemAdd(const ImRect&, ImGuiID, const ImRect*, ImGuiItemFlags): Assertion `id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!"' failed.

Rebuilding with debug flags and using gdb I found that this is triggered when the tracking system returns a source with an empty name.

I made this patch that stopped the problem, but I don't know if this is an appropriate solution for this problem.

```d
diff --git a/source/session/panels/tracking.d b/source/session/panels/tracking.d
index e0b713f..c3e2e89 100644
--- a/source/session/panels/tracking.d
+++ b/source/session/panels/tracking.d
@@ -137,7 +137,9 @@ private:
                             uiImEndMenu();
                         }
                     } else {
-                        if (uiImSelectable(source.cName, selected)) {
+                        if (uiImSelectable(
+                                source.name.length > 0 ? source.cName : " ".ptr, 
+                                selected)) {
                             binding.sourceType = SourceType.Blendshape;
                             binding.sourceName = source.name;
                             binding.createSourceDisplayName();
```

This was tested on the binary provided by the 0.0.1 AppImage using a compiled cimage.so and on a Fedora 36 environment.

**Comment by grillo-delmal** [comment]
For reference, this is the full backtrace

```c
(gdb) bt
#0  0x00007ffff772dc4c in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff76dd9c6 in raise () at /lib64/libc.so.6
#2  0x00007ffff76c77f4 in abort () at /lib64/libc.so.6
#3  0x00007ffff76c771b in _nl_load_domain.cold () at /lib64/libc.so.6
#4  0x00007ffff76d6576 in  () at /lib64/libc.so.6
#5  0x00007fffe333d97c in ImGui::ItemAdd(ImRect const&, unsigned int, ImRect const*, int) (bb=..., id=2362583023, nav_bb_arg=0x0, extra_flags=0)
    at /opt/src/bindbc-imgui/deps/cimgui/imgui/imgui.cpp:8925
#6  0x00007fffe33e0054 in ImGui::Selectable(char const*, bool, int, ImVec2 const&) (label=0x7ffff7e8c9c9 "", selected=true, flags=0, size_arg=...)
    at /opt/src/bindbc-imgui/deps/cimgui/imgui/imgui_widgets.cpp:6233
#7  0x00007fffe330c668 in igSelectable_Bool(char const*, bool, ImGuiSelectableFlags, ImVec2) (label=0x7ffff7e8c9c9 "", selected=true, flags=0, size=...)
    at /opt/src/bindbc-imgui/deps/cimgui/cimgui.cpp:961
#8  0x00000000004f72d5 in _D6bindbc5imgui4bindQl12igSelectableFPxabEQBoQBkQBhQBq20ImGuiSelectableFlagsxSQCyQCuQCrQDa6ImVec2Zb
    (label=0x7ffff7e8c9c9 "", selected=true, flags=bindbc.imgui.bind.imgui.None, size=...) at ../bindbc-imgui/source/bindbc/imgui/bind/imgui.d:7507
#9  0x00000000004f66b4 in _D4inui7widgets5input14uiImSelectableFPxabZb (name=0x7ffff7e8c9c9 "", selected=true) at ../inui/source/inui/widgets/input.d:168
#10 0x000000000043c5bf in _D7session6panels8tracking13TrackingPanel12ratioBindingMFmKCQCgQBu15TrackingBindingZv
    (this=0x7ffff759a100, i=0, binding=@0x7ffff75b30e0: 0x7ffff75ad420) at source/session/panels/tracking.d:140
#11 0x000000000043b7bd in _D7session6panels8tracking13TrackingPanel8onUpdateMFZv (this=0x7ffff759a100) at source/session/panels/tracking.d:216
#12 0x00000000004f44b8 in _D4inui5panel5Panel6updateMFZv (this=0x7ffff759a100) at ../inui/source/inui/panel.d:112
#13 0x00000000004f45af in _D4inui5panel14inUpdatePanelsFZv () at ../inui/source/inui/panel.d:144
#14 0x00000000004f3d11 in _D4inui4core6window6appwin19InApplicationWindow6updateMFZv (this=0x7ffff759a400) at ../inui/source/inui/core/window/appwin.d:340
#15 0x000000000048e293 in _Dmain (args=...) at source/app.d:44
```

**Comment by LunaTheFoxgirl** [comment]
I've made a more sensible patch here, could you check if it works for you? https://github.com/Inochi2D/inochi-session/commit/91e2e7f86feba592b997886b1efdd409d50fbeee

**Comment by LunaTheFoxgirl** [comment]
Appears to be fixed by https://github.com/Inochi2D/inui/commit/c4f62ab53c8eac0d30a096d9c3bb9008b6238637
